/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nsu_fit_CpuInfo */

#ifndef _Included_nsu_fit_CpuInfo
#define _Included_nsu_fit_CpuInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nsu_fit_CpuInfo
 * Method:    getInstance
 * Signature: ()Lnsu/fit/CpuInfo;
 */
JNIEXPORT jobject JNICALL Java_nsu_fit_CpuInfo_getInstance
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
